roles:
  - src: https://github.com/digimokan/ans_role_add_group
  - src: https://github.com/digimokan/ans_role_add_user
  - src: https://github.com/digimokan/ans_role_config_bash
  - src: https://github.com/digimokan/ans_role_config_boot_messages
  - src: https://github.com/digimokan/ans_role_config_mate_de
  - src: https://github.com/digimokan/ans_role_config_pkg_repo_list_updates
  - src: https://github.com/digimokan/ans_role_config_sound
  - src: https://github.com/digimokan/ans_role_config_sudo
  - src: https://github.com/digimokan/ans_role_config_time
  - src: https://github.com/digimokan/ans_role_config_unofficial_packages
  - src: https://github.com/digimokan/ans_role_config_video_drivers
  - src: https://github.com/digimokan/ans_role_config_xdg_user_dirs
  - src: https://github.com/digimokan/ans_role_cpu_microcode
  - src: https://github.com/digimokan/ans_role_pacnew_ignore

