roles:
  - src: https://github.com/digimokan/ans_role_add_group
  - src: https://github.com/digimokan/ans_role_add_user
  - src: https://github.com/digimokan/ans_role_config_time
  - src: https://github.com/digimokan/ans_role_cpu_microcode
  - src: https://github.com/digimokan/ans_role_update_repo_servers

